const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description:
      "Relax in a peaceful beachfront cottage with beautiful ocean views.",
    image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b",
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern City Apartment",
    description: "Stylish apartment located in the heart of the city.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    price: 2200,
    location: "New York",
    country: "United States",
  },
  {
    title: "Mountain Retreat Cabin",
    description: "A cozy wooden cabin surrounded by breathtaking mountains.",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
    price: 1800,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Luxury Villa",
    description: "Spacious luxury villa with a private swimming pool.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    price: 5000,
    location: "Dubai",
    country: "United Arab Emirates",
  },
  {
    title: "Lake View Cottage",
    description: "Beautiful cottage beside a peaceful lake.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
    price: 1700,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Desert Camp",
    description: "Experience luxury camping in the middle of the desert.",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9",
    price: 1300,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Forest Treehouse",
    description: "Unique treehouse surrounded by lush green forests.",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    price: 1200,
    location: "Kerala",
    country: "India",
  },
  {
    title: "Beach Resort",
    description: "Luxury resort with direct access to the beach.",
    image: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd",
    price: 3500,
    location: "Goa",
    country: "India",
  },
  {
    title: "Swiss Chalet",
    description: "Traditional chalet with amazing mountain scenery.",
    image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb",
    price: 4200,
    location: "Zermatt",
    country: "Switzerland",
  },
  {
    title: "Safari Lodge",
    description: "Stay close to wildlife in this luxury safari lodge.",
    image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e",
    price: 3800,
    location: "Serengeti",
    country: "Tanzania",
  },
  {
    title: "Historic Cottage",
    description: "A charming historic home with classic architecture.",
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4",
    price: 2100,
    location: "London",
    country: "United Kingdom",
  },
  {
    title: "Private Island Villa",
    description: "Enjoy complete privacy on your own island.",
    image: "https://images.unsplash.com/photo-1618140052121-39fc6db33972",
    price: 10000,
    location: "Maldives",
    country: "Maldives",
  },
  {
    title: "Luxury Penthouse",
    description: "Modern penthouse with panoramic skyline views.",
    image: "https://images.unsplash.com/photo-1602088113235-229c19758e9f",
    price: 4800,
    location: "Singapore",
    country: "Singapore",
  },
  {
    title: "Historic Castle",
    description: "Stay in a restored medieval castle.",
    image: "https://images.unsplash.com/photo-1533619239233-6280475a633a",
    price: 5500,
    location: "Edinburgh",
    country: "United Kingdom",
  },
  {
    title: "Beach Bungalow",
    description: "Simple and relaxing bungalow near the beach.",
    image: "https://images.unsplash.com/photo-1602391833977-358a52198938",
    price: 1600,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Mountain Cabin",
    description: "Escape into nature with this mountain cabin.",
    image: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb",
    price: 2000,
    location: "Banff",
    country: "Canada",
  },
  {
    title: "City Studio",
    description: "Compact studio apartment perfect for solo travelers.",
    image: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9",
    price: 1400,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Luxury Beach Villa",
    description: "Beachfront villa with an infinity pool.",
    image: "https://images.unsplash.com/photo-1585543805890-6051f7829f98",
    price: 6200,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Eco Forest Retreat",
    description: "Eco-friendly stay surrounded by nature.",
    image: "https://images.unsplash.com/photo-1518684079-3c830dcef090",
    price: 1100,
    location: "Costa Rica",
    country: "Costa Rica",
  },
  {
    title: "Luxury Farmhouse",
    description: "Peaceful farmhouse with modern amenities.",
    image: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f",
    price: 2500,
    location: "Punjab",
    country: "India",
  },
];

module.exports = { data: sampleListings };
